spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipelounge
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop # validate - for production stage
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

#server:
  #address: 0.0.0.0
  #port: 8080
